CREATE TABLE Cats4(
	ID INT NOT NULL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL DEFAULT 'Unknown',
    Age INT NOT NULL DEFAULT 00
);

INSERT INTO cats4(ID, Name, Age)
VALUES (1, 'Mickey', 10);

INSERT INTO cats4(ID)
VALUES(2);

SELECT * FROM Cats4;
